# Attention Mask for SDPA

Short notebook to play with how to make masks for SDPA

In [3]:
import torch
import torch.nn.functional as F

In [1]:
Tq = 5
Tk = 8

In [9]:
row_idx = (Tk-Tq) + torch.arange(Tq)
row_idx = row_idx.unsqueeze(1)
row_idx

tensor([[3],
        [4],
        [5],
        [6],
        [7]])

In [10]:
col_idx = torch.arange(Tk).unsqueeze(0)
col_idx

tensor([[0, 1, 2, 3, 4, 5, 6, 7]])

In [16]:
attention_mask = col_idx <= row_idx
attention_mask.to(torch.int64)

tensor([[1, 1, 1, 1, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])

In [21]:
window = 2

in_window_mask = (row_idx - col_idx) <= window
in_window_mask.to(torch.int64)

tensor([[0, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 1, 1, 1]])

In [22]:
final_mask = attention_mask & in_window_mask
final_mask.to(torch.int64)

tensor([[0, 1, 1, 1, 0, 0, 0, 0],
        [0, 0, 1, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 1, 0, 0],
        [0, 0, 0, 0, 1, 1, 1, 0],
        [0, 0, 0, 0, 0, 1, 1, 1]])